name: Branch and Path Filtering

on:
    push:
        branches:
            - dev
        paths:
            - 'src/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2 
