name: Multi-Shell Hello World
on:
  push:
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
        - name: Print Hello World using Python
          run: print'Hello World!'
          shell: python
        - name: Print Hello World using Bash
          run: echo "Hello World!"
          shell: bash
        - name: Print Hello World using PowerShell
          run: Write-Host "Hello World!"
          shell: pwsh

