name: Pull Request with Path Filtering
on:
    pull_request:
        types: [opened, synchronize, reopened ,closed]
        branches:
            - main
        paths:
            - 'src/**'

jobs:
    printhello:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello
              run: echo "Hello, this PR affects files in the src directory!"    
